[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "enhanced-oauth-backend"

[services.variables]
PORT = "3000"
NODE_ENV = "production"
